import '@/styles/globals.scss';
import React from 'react';

export const metadata = {
  title: 'Template NextJS Login',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
      </body>
    </html>
  )
}
