import Head from "next/head"
import '@/styles/global.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>Template NextJS Login</title>
      </Head>
      <body>{children}</body>
    </html>
  )
}
